free_world: world
free_respawn: true
free_tppearl: true
damagelog_min: 3
damagelog_ticks: 600
ppkill_enabled: true
prisonerstealing_enabled: true
resetbed_enable: false
summon_damage_radius: 20
summon_damage_ticks: 20
summon_damage_amt: 2
prison_world: world_the_end
prison_motd:
   - You are trapped in this bleak and endless world
   - by a prison pearl.
   - Type /pplocate to locate your pearl.
prison_grant_perms:
   - RandomSpawn.exclude
save_ticks: 2400